services:
  gateway-public:
    volumes:
      - .:/app

  gateway-ops:
    volumes:
      - .:/app

  gateway-internal:
    volumes:
      - .:/app

  scheduler:
    volumes:
      - .:/app

  sse-server:
    volumes:
      - .:/app
