export type TabType = 'matchmaker' | 'relationships' | 'profile'

export type SubView =
  | 'main'
  | 'candidate-detail'
  | 'chat'
  | 'verification'
  | 'collected-preferences'
  | 'edit-profile'
  | 'settings'

export type AppPage =
  | 'splash'
  | 'auth-welcome'
  | 'auth-one-click'
  | 'auth-phone'
  | 'auth-verification-code'
  | 'auth-wechat-binding'
  | 'auth-new-user-welcome'
  | 'auth-onboarding'
  | 'auth-recovery'
  | 'main-matchmaker'
  | 'main-relationships'
  | 'main-profile'
  | 'sub-candidate-detail'
  | 'sub-chat'
  | 'sub-verification'
  | 'sub-collected-preferences'
  | 'sub-edit-profile'
  | 'sub-settings'
  | 'ops-workbench'
