type NotificationParams = {
  userId?: string
  profileId: number
  submissionId: string
  decision: 'approve' | 'reject' | 'request_resubmission'
  approvedValue?: string
  requestedDocuments?: string[]
  reviewNote?: string
}

/**
 * 生成审核结果通知消息
 */
function generateNotificationMessage(params: NotificationParams): string {
  switch (params.decision) {
    case 'approve':
      return `您的学历认证已通过审核，认证学历为：${params.approvedValue || '已确认'}。感谢您的配合！`
    case 'reject':
      return `您的学历认证审核未通过。原因：${params.reviewNote || '材料不符合要求'}。请重新提交认证材料。`
    case 'request_resubmission':
      const docs = params.requestedDocuments?.join('、') || '补充材料'
      return `您的学历认证需要补充材料。请补充以下文件：${docs}。`
    default:
      return '您的学历认证状态已更新。'
  }
}

/**
 * 发送审核结果通知（自动调用）
 */
export async function notifyVerificationResult(params: NotificationParams): Promise<void> {
  if (!params.userId) {
    console.warn('无法发送通知：缺少user_id')
    return
  }

  // Notifications are now generated by the backend during review processing.
  // Keep the formatted message for debugging so reviewers still see what was communicated.
  console.log('审核通知由后端自动生成:', {
    submissionId: params.submissionId,
    userId: params.userId,
    message: generateNotificationMessage(params),
  })
}
