"""Partner chat subsystem: threads, messages, risk controls, and summaries."""

from pathlib import Path

from ._path_bootstrap import ensure_her_repo_on_sys_path

ensure_her_repo_on_sys_path(Path(__file__))

from .conversations import (
    CONV_KIND_DM,
    CONV_KIND_GROUP,
    LAYOUT_ROLE_ASSISTANT_DM_A,
    LAYOUT_ROLE_ASSISTANT_DM_B,
    LAYOUT_ROLE_MAIN_GROUP,
    ROLE_AGENT,
    ROLE_HUMAN,
    ROLE_SYSTEM,
    SOURCE_AGENT,
    SOURCE_SYSTEM,
    SOURCE_USER,
    build_case_conversation_timeline,
    create_assistant_case_layout,
    get_conversation,
    get_conversation_by_case_and_key,
    get_conversation_member,
    get_or_create_conversation,
    list_case_conversations,
    list_conversation_members,
    list_conversation_messages,
    post_conversation_message,
)
from .assistant_orchestrator import process_pending_agent_tasks
from .assistant_sessions import (
    close_idle_agent_sessions,
    get_agent_session,
    get_agent_session_by_case,
    get_agent_task,
    list_agent_tasks,
)
from .fraud_graph import (
    build_fraud_network_overview,
    evaluate_fraud_network,
    get_fraud_network_profile,
    list_fraud_network_links,
    list_fraud_network_profiles,
    record_fraud_network_observation,
)
from .maintenance import run_chat_maintenance
from .moderation_ops import (
    build_risk_case_playback,
    build_risk_weekly_dashboard,
    batch_review_risk_cases,
    get_risk_appeal,
    list_risk_appeals,
    review_risk_appeal,
    submit_risk_appeal,
)
from .outbox_admin import (
    list_processing_outbox,
    list_failed_outbox,
    list_pending_outbox,
    list_retry_pending_outbox,
    requeue_outbox_rows,
    summarize_outbox,
)
from .outbox_worker import run_chat_outbox_worker, serve_chat_outbox_worker
from .profile_reviews import (
    dispute_profile_field_verification,
    expire_due_profile_field_verifications,
    evaluate_profile_consistency,
    field_verification_policies,
    get_photo_risk_review_queue_item,
    get_photo_risk_score_run,
    get_profile_field_verification_submission,
    get_profile_review_case_appeal,
    get_profile_review_case,
    list_photo_risk_review_queue,
    list_photo_risk_score_runs,
    list_profile_review_case_appeals,
    list_profile_field_verification_submissions,
    list_profile_review_cases,
    list_profile_review_events,
    resubmit_profile_field_verification,
    review_profile_field_verification,
    review_profile_review_case_appeal,
    review_profile_review_case,
    submit_profile_review_case_appeal,
    submit_profile_field_verification,
)
from .self_service import build_user_trust_hub
from .risk import (
    build_thread_risk_overview,
    get_risk_case,
    list_member_reports,
    list_meeting_feedback,
    list_risk_cases,
    list_risk_signals,
    review_risk_case,
    submit_meeting_feedback,
    submit_member_report,
)
from .service import (
    SRC_SYSTEM,
    SRC_USER,
    VIS_DYADIC,
    VIS_OWNER_ONLY,
    VIS_SYSTEM,
    current_time,
    get_or_create_thread,
    get_thread,
    get_thread_by_case,
    list_messages,
    post_message,
)
from .storage import (
    connect_db,
    initialize_database,
    reset_all_tables,
)
from .summaries import get_thread_summary
from .timeline import build_chat_timeline
from .verification import (
    create_live_video_verification_challenge,
    get_verification_submission,
    list_photo_review_requests,
    list_verification_assets,
    list_verification_notifications,
    list_verification_reviews,
    list_verification_submissions,
    request_live_video_verification,
    resubmit_live_video_verification,
    review_live_video_verification,
    submit_live_video_verification,
)

__all__ = [
    "CONV_KIND_DM",
    "CONV_KIND_GROUP",
    "LAYOUT_ROLE_ASSISTANT_DM_A",
    "LAYOUT_ROLE_ASSISTANT_DM_B",
    "LAYOUT_ROLE_MAIN_GROUP",
    "ROLE_AGENT",
    "ROLE_HUMAN",
    "ROLE_SYSTEM",
    "SRC_SYSTEM",
    "SRC_USER",
    "SOURCE_AGENT",
    "SOURCE_SYSTEM",
    "SOURCE_USER",
    "VIS_DYADIC",
    "VIS_OWNER_ONLY",
    "VIS_SYSTEM",
    "build_case_conversation_timeline",
    "build_thread_risk_overview",
    "build_chat_timeline",
    "build_fraud_network_overview",
    "build_risk_case_playback",
    "build_risk_weekly_dashboard",
    "build_user_trust_hub",
    "batch_review_risk_cases",
    "close_idle_agent_sessions",
    "connect_db",
    "current_time",
    "create_live_video_verification_challenge",
    "create_assistant_case_layout",
    "dispute_profile_field_verification",
    "evaluate_profile_consistency",
    "expire_due_profile_field_verifications",
    "evaluate_fraud_network",
    "field_verification_policies",
    "get_photo_risk_review_queue_item",
    "get_photo_risk_score_run",
    "get_agent_session",
    "get_agent_session_by_case",
    "get_agent_task",
    "get_conversation",
    "get_conversation_by_case_and_key",
    "get_conversation_member",
    "get_or_create_conversation",
    "get_profile_field_verification_submission",
    "get_profile_review_case_appeal",
    "get_profile_review_case",
    "get_or_create_thread",
    "get_fraud_network_profile",
    "get_risk_case",
    "get_thread",
    "get_thread_summary",
    "get_thread_by_case",
    "initialize_database",
    "list_case_conversations",
    "list_agent_tasks",
    "list_conversation_members",
    "list_conversation_messages",
    "list_fraud_network_links",
    "list_fraud_network_profiles",
    "list_member_reports",
    "list_meeting_feedback",
    "list_messages",
    "list_failed_outbox",
    "list_pending_outbox",
    "list_processing_outbox",
    "list_retry_pending_outbox",
    "list_photo_risk_review_queue",
    "list_photo_risk_score_runs",
    "list_photo_review_requests",
    "list_profile_field_verification_submissions",
    "list_profile_review_case_appeals",
    "list_profile_review_cases",
    "list_profile_review_events",
    "list_risk_appeals",
    "list_risk_cases",
    "list_risk_signals",
    "list_verification_assets",
    "list_verification_notifications",
    "list_verification_reviews",
    "list_verification_submissions",
    "post_conversation_message",
    "post_message",
    "process_pending_agent_tasks",
    "requeue_outbox_rows",
    "reset_all_tables",
    "request_live_video_verification",
    "record_fraud_network_observation",
    "resubmit_profile_field_verification",
    "resubmit_live_video_verification",
    "review_risk_appeal",
    "review_profile_field_verification",
    "review_profile_review_case_appeal",
    "review_profile_review_case",
    "review_risk_case",
    "review_live_video_verification",
    "run_chat_maintenance",
    "run_chat_outbox_worker",
    "serve_chat_outbox_worker",
    "submit_risk_appeal",
    "submit_profile_field_verification",
    "submit_profile_review_case_appeal",
    "submit_live_video_verification",
    "submit_meeting_feedback",
    "submit_member_report",
    "summarize_outbox",
    "get_risk_appeal",
    "get_verification_submission",
]
