#!/usr/bin/env python3

import argparse
from datetime import datetime, timedelta

from backfill_profile_enrichment import ALL_NEW_COLUMNS


PROFILE_COLUMNS = [
    "id",
    "name",
    "avatar_url",
    "photo_count",
    "gender",
    "age",
    "city",
    "district",
    "hometown",
    "settlement_city",
    "housing_status",
    "car_status",
    "height",
    "education",
    "job",
    "income_range",
    "relationship_goal",
    "preferred_age_min",
    "preferred_age_max",
    "preferred_cities",
    "preferred_height_min",
    "preferred_height_max",
    "preferred_education_min",
    "preferred_income_min_wan",
    "preferred_income_max_wan",
    "personality",
    "values",
    "lifestyle",
    "hobbies",
    "smoking",
    "drinking",
    "long_distance",
    "accept_long_distance",
    "accept_smoking",
    "accept_drinking",
    "accept_marital_status",
    "marital_status",
    "has_children",
    "children_count",
    "children_living_with_self",
    "want_children",
    "accept_partner_children",
    "marriage_timeline",
    "family_background",
    "notes",
    "profile_status",
    "last_active_at",
    "verified_level",
    "source_channel",
    "created_at",
    "updated_at",
    "preferred_age_strictness",
    "preferred_height_strictness",
    "preferred_education_strictness",
    "preferred_income_strictness",
    "life_routine",
    "communication_style",
    "dating_pace",
    "expression_style",
    "relationship_capacity",
    "accept_marital_status_strength",
    "accept_partner_children_strength",
    "interaction_comfort",
    "patience_level",
    "life_texture",
    "career_intensity",
    "exercise_habit",
    "growth_signal",
    "warmth_style",
    "aesthetic_expression",
    "conversation_resonance",
    "personal_presence",
    "blended_family_readiness",
]

STRUCTURED_COLUMN_TYPES = {
    "growth_signal": "VARCHAR(32)",
    "warmth_style": "VARCHAR(32)",
    "aesthetic_expression": "VARCHAR(32)",
    "conversation_resonance": "VARCHAR(32)",
    "personal_presence": "VARCHAR(32)",
    "blended_family_readiness": "VARCHAR(32)",
}


def parse_args():
    parser = argparse.ArgumentParser(description="Seed curated gap-filling profiles into MySQL.")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=3307)
    parser.add_argument("--user", default="root")
    parser.add_argument("--password", default="")
    parser.add_argument("--database", default="her")
    parser.add_argument("--table", default="profiles")
    parser.add_argument("--photos-table", default="profile_photos")
    parser.add_argument("--charset", default="utf8mb4")
    return parser.parse_args()


def money_range(min_wan, max_wan):
    return f"{min_wan}-{max_wan}万/年"


def iso(dt):
    return dt.strftime("%Y-%m-%d %H:%M:%S")


def base_profile(
    *,
    profile_id,
    name,
    gender,
    age,
    city,
    district,
    height,
    education,
    job,
    income_min,
    income_max,
    relationship_goal,
    personality,
    values,
    lifestyle,
    hobbies,
    notes,
    preferred_age_min,
    preferred_age_max,
    preferred_height_min,
    preferred_height_max,
    preferred_education_min,
    preferred_income_min_wan,
    preferred_income_max_wan,
    life_routine,
    communication_style,
    dating_pace,
    expression_style,
    relationship_capacity,
    interaction_comfort,
    patience_level,
    life_texture,
    career_intensity,
    exercise_habit,
    growth_signal,
    warmth_style,
    aesthetic_expression,
    blended_family_readiness,
    conversation_resonance="偏务实日常",
    personal_presence="温和耐看",
    settlement_city=None,
    hometown=None,
    smoking="否",
    drinking="偶尔",
    long_distance="可协商",
    accept_long_distance="可协商",
    accept_smoking="不接受",
    accept_drinking="接受",
    accept_marital_status="未婚",
    accept_marital_status_strength="未知",
    marital_status="未婚",
    has_children=0,
    children_count=0,
    children_living_with_self=0,
    want_children="想要",
    accept_partner_children="未知",
    accept_partner_children_strength="未知",
    marriage_timeline="1年内",
    family_background="家庭关系简单",
    housing_status="已购房",
    car_status="有车",
    photo_count=6,
    verified_level="id",
    source_channel="高质量补池",
    preferred_cities=None,
    profile_status="active",
    preferred_age_strictness="可放宽",
    preferred_height_strictness="可放宽",
    preferred_education_strictness="仅参考",
    preferred_income_strictness="仅参考",
    created_at=None,
    updated_at=None,
    last_active_at=None,
):
    created_at = created_at or datetime(2026, 4, 25, 10, 0, 0)
    updated_at = updated_at or created_at
    last_active_at = last_active_at or updated_at
    avatar_url = f"https://img.her.local/seed/{profile_id}/avatar.jpg"
    return {
        "id": profile_id,
        "name": name,
        "avatar_url": avatar_url,
        "photo_count": photo_count,
        "gender": gender,
        "age": age,
        "city": city,
        "district": district,
        "hometown": hometown or city,
        "settlement_city": settlement_city or city,
        "housing_status": housing_status,
        "car_status": car_status,
        "height": height,
        "education": education,
        "job": job,
        "income_range": money_range(income_min, income_max),
        "relationship_goal": relationship_goal,
        "preferred_age_min": preferred_age_min,
        "preferred_age_max": preferred_age_max,
        "preferred_cities": preferred_cities or city,
        "preferred_height_min": preferred_height_min,
        "preferred_height_max": preferred_height_max,
        "preferred_education_min": preferred_education_min,
        "preferred_income_min_wan": preferred_income_min_wan,
        "preferred_income_max_wan": preferred_income_max_wan,
        "personality": personality,
        "values": values,
        "lifestyle": lifestyle,
        "hobbies": hobbies,
        "smoking": smoking,
        "drinking": drinking,
        "long_distance": long_distance,
        "accept_long_distance": accept_long_distance,
        "accept_smoking": accept_smoking,
        "accept_drinking": accept_drinking,
        "accept_marital_status": accept_marital_status,
        "marital_status": marital_status,
        "has_children": has_children,
        "children_count": children_count,
        "children_living_with_self": children_living_with_self,
        "want_children": want_children,
        "accept_partner_children": accept_partner_children,
        "marriage_timeline": marriage_timeline,
        "family_background": family_background,
        "notes": notes,
        "profile_status": profile_status,
        "last_active_at": iso(last_active_at),
        "verified_level": verified_level,
        "source_channel": source_channel,
        "created_at": iso(created_at),
        "updated_at": iso(updated_at),
        "preferred_age_strictness": preferred_age_strictness,
        "preferred_height_strictness": preferred_height_strictness,
        "preferred_education_strictness": preferred_education_strictness,
        "preferred_income_strictness": preferred_income_strictness,
        "life_routine": life_routine,
        "communication_style": communication_style,
        "dating_pace": dating_pace,
        "expression_style": expression_style,
        "relationship_capacity": relationship_capacity,
        "accept_marital_status_strength": accept_marital_status_strength,
        "accept_partner_children_strength": accept_partner_children_strength,
        "interaction_comfort": interaction_comfort,
        "patience_level": patience_level,
        "life_texture": life_texture,
        "career_intensity": career_intensity,
        "exercise_habit": exercise_habit,
        "growth_signal": growth_signal,
        "warmth_style": warmth_style,
        "aesthetic_expression": aesthetic_expression,
        "conversation_resonance": conversation_resonance,
        "personal_presence": personal_presence,
        "blended_family_readiness": blended_family_readiness,
    }


def make_photo_rows(profile):
    created_at = profile["created_at"]
    updated_at = profile["updated_at"]
    rows = [
        {
            "profile_id": profile["id"],
            "photo_url": profile["avatar_url"],
            "photo_type": "avatar",
            "sort_order": 0,
            "is_primary": 1,
            "created_at": created_at,
            "updated_at": updated_at,
        }
    ]
    for idx in range(1, int(profile["photo_count"]) + 1):
        rows.append(
            {
                "profile_id": profile["id"],
                "photo_url": f"https://img.her.local/seed/{profile['id']}/{idx}.jpg",
                "photo_type": "gallery",
                "sort_order": idx,
                "is_primary": 0,
                "created_at": created_at,
                "updated_at": updated_at,
            }
        )
    return rows


def build_profiles():
    now = datetime(2026, 4, 29, 22, 0, 0)
    return [
        base_profile(
            profile_id=30001,
            name="顾闻舟",
            gender="男",
            age=34,
            city="上海",
            district="徐汇区",
            height=181,
            education="硕士",
            job="AI产品经理",
            income_min=58,
            income_max=88,
            relationship_goal="结婚导向",
            personality="情绪稳定, 真诚, 有责任感",
            values="消费观正常, 愿意共同经营生活, 不喜欢攀比",
            lifestyle="规律作息, 喜欢做饭, 爱运动",
            hobbies="阅读, 看展, 徒步",
            notes="在上海长期定居，平时会看展和做饭，希望关系里有稳定推进也有生活趣味",
            preferred_age_min=28,
            preferred_age_max=34,
            preferred_height_min=160,
            preferred_height_max=174,
            preferred_education_min="本科",
            preferred_income_min_wan=20,
            preferred_income_max_wan=120,
            life_routine="生活规律",
            communication_style="主动沟通",
            dating_pace="认真推进",
            expression_style="会表达有生活感",
            relationship_capacity="稳定投入关系",
            interaction_comfort="相处轻松",
            patience_level="高耐心",
            life_texture="有见识也有生活感",
            career_intensity="脑力投入型",
            exercise_habit="规律运动",
            growth_signal="上升明确",
            warmth_style="有温度会接话",
            aesthetic_expression="有审美输出",
            conversation_resonance="能聊想法也能聊日常",
            personal_presence="有记忆点",
            blended_family_readiness="愿意一起商量",
            accept_marital_status="未婚, 离异未育",
            marriage_timeline="1年内",
            verified_level="id",
            last_active_at=now - timedelta(hours=3),
        ),
        base_profile(
            profile_id=30002,
            name="陆景珩",
            gender="男",
            age=33,
            city="上海",
            district="长宁区",
            height=179,
            education="硕士",
            job="医疗器械产品经理",
            income_min=46,
            income_max=72,
            relationship_goal="结婚导向",
            personality="情绪稳定, 理性, 温和",
            values="消费观正常, 能沟通, 对感情认真",
            lifestyle="规律作息, 爱运动, 喜欢做饭",
            hobbies="游泳, 电影, 咖啡",
            notes="能理解医生值班和临时加班，忙的时候也愿意提前协调见面",
            preferred_age_min=28,
            preferred_age_max=34,
            preferred_height_min=160,
            preferred_height_max=173,
            preferred_education_min="硕士",
            preferred_income_min_wan=25,
            preferred_income_max_wan=120,
            life_routine="节奏偏忙但可协调",
            communication_style="主动沟通",
            dating_pace="认真推进",
            expression_style="会表达有生活感",
            relationship_capacity="稳定投入关系",
            interaction_comfort="安静低压",
            patience_level="高耐心",
            life_texture="有见识也有生活感",
            career_intensity="高强度但可协调",
            exercise_habit="规律运动",
            growth_signal="上升明确",
            warmth_style="理性但不冷",
            aesthetic_expression="有生活审美",
            conversation_resonance="会接话也会接情绪",
            personal_presence="温和耐看",
            blended_family_readiness="愿意一起商量",
            accept_marital_status="未婚, 离异未育",
            marriage_timeline="1年内",
            verified_level="offline",
            last_active_at=now - timedelta(hours=5),
        ),
        base_profile(
            profile_id=30003,
            name="许之衡",
            gender="男",
            age=29,
            city="上海",
            district="静安区",
            height=178,
            education="硕士",
            job="品牌策略顾问",
            income_min=32,
            income_max=52,
            relationship_goal="认真恋爱",
            personality="情绪稳定, 细腻, 善沟通",
            values="消费观正常, 能沟通, 尊重彼此空间",
            lifestyle="周末会出门走走, 喜欢咖啡馆, 规律作息",
            hobbies="看展, 摄影, 烘焙",
            notes="喜欢逛展和拍照，也愿意把日常过得有一点审美和趣味",
            preferred_age_min=25,
            preferred_age_max=31,
            preferred_height_min=158,
            preferred_height_max=172,
            preferred_education_min="本科",
            preferred_income_min_wan=15,
            preferred_income_max_wan=80,
            life_routine="生活规律",
            communication_style="主动沟通",
            dating_pace="自然推进",
            expression_style="会表达有生活感",
            relationship_capacity="自然稳定投入",
            interaction_comfort="相处轻松",
            patience_level="耐心稳定",
            life_texture="有见识也有生活感",
            career_intensity="常规稳定",
            exercise_habit="轻运动",
            growth_signal="平台成熟",
            warmth_style="有温度会接话",
            aesthetic_expression="有审美输出",
            conversation_resonance="能聊想法也能聊日常",
            personal_presence="有记忆点",
            blended_family_readiness="愿意一起商量",
            marriage_timeline="2年内",
            verified_level="offline",
            last_active_at=now - timedelta(hours=7),
        ),
        base_profile(
            profile_id=30004,
            name="沈叙白",
            gender="男",
            age=32,
            city="南京",
            district="建邺区",
            height=180,
            education="硕士",
            job="产业战略经理",
            income_min=48,
            income_max=72,
            relationship_goal="结婚导向",
            personality="情绪稳定, 理性, 有主见",
            values="消费观正常, 不拜金, 对感情认真",
            lifestyle="规律作息, 爱运动, 喜欢做饭",
            hobbies="阅读, 看展, 徒步",
            notes="做战略相关工作，重视长期成长，也希望关系里既能沟通现实也能聊想法",
            preferred_age_min=27,
            preferred_age_max=34,
            preferred_height_min=160,
            preferred_height_max=173,
            preferred_education_min="硕士",
            preferred_income_min_wan=35,
            preferred_income_max_wan=120,
            life_routine="生活规律",
            communication_style="主动沟通",
            dating_pace="认真推进",
            expression_style="会表达有生活感",
            relationship_capacity="稳定投入关系",
            interaction_comfort="有边界不拧巴",
            patience_level="耐心稳定",
            life_texture="有见识也有生活感",
            career_intensity="脑力投入型",
            exercise_habit="规律运动",
            growth_signal="上升明确",
            warmth_style="理性但不冷",
            aesthetic_expression="有审美输出",
            conversation_resonance="能聊想法也能聊日常",
            personal_presence="有记忆点",
            blended_family_readiness="愿意一起商量",
            accept_marital_status="未婚, 离异未育",
            verified_level="offline",
            last_active_at=now - timedelta(hours=1),
        ),
        base_profile(
            profile_id=30005,
            name="顾景尧",
            gender="男",
            age=33,
            city="南京",
            district="鼓楼区",
            height=182,
            education="博士",
            job="用户研究负责人",
            income_min=42,
            income_max=66,
            relationship_goal="结婚导向",
            personality="真诚, 情绪稳定, 有耐心",
            values="三观正, 愿意共同经营生活, 边界清楚",
            lifestyle="规律作息, 喜欢咖啡馆, 偶尔短途旅行",
            hobbies="阅读, 咖啡, 手工",
            notes="偏理性但不木，平时会看书写点东西，也重视两个人持续成长",
            preferred_age_min=27,
            preferred_age_max=34,
            preferred_height_min=160,
            preferred_height_max=173,
            preferred_education_min="硕士",
            preferred_income_min_wan=30,
            preferred_income_max_wan=110,
            life_routine="生活规律",
            communication_style="稳定沟通",
            dating_pace="认真推进",
            expression_style="会表达有生活感",
            relationship_capacity="稳定投入关系",
            interaction_comfort="安静低压",
            patience_level="高耐心",
            life_texture="有见识也有生活感",
            career_intensity="脑力投入型",
            exercise_habit="轻运动",
            growth_signal="上升明确",
            warmth_style="理性但不冷",
            aesthetic_expression="有审美输出",
            conversation_resonance="能聊想法也能聊日常",
            personal_presence="有记忆点",
            blended_family_readiness="愿意一起商量",
            verified_level="id",
            last_active_at=now - timedelta(hours=2),
        ),
        base_profile(
            profile_id=30006,
            name="程叙安",
            gender="男",
            age=37,
            city="杭州",
            district="西湖区",
            height=176,
            education="本科",
            job="高校行政",
            income_min=24,
            income_max=38,
            relationship_goal="结婚导向",
            personality="情绪稳定, 有耐心, 真诚",
            values="重视家庭, 愿意共同经营生活, 稳定踏实",
            lifestyle="生活规律, 喜欢做饭, 周末会出门走走",
            hobbies="散步, 电影, 桌游",
            notes="能接受对方带孩子，愿意提前商量接送、周末安排和与老人相处边界",
            preferred_age_min=32,
            preferred_age_max=38,
            preferred_height_min=155,
            preferred_height_max=170,
            preferred_education_min="大专",
            preferred_income_min_wan=15,
            preferred_income_max_wan=60,
            life_routine="生活规律",
            communication_style="稳定沟通",
            dating_pace="认真推进",
            expression_style="自然表达",
            relationship_capacity="稳定投入关系",
            interaction_comfort="相处轻松",
            patience_level="高耐心",
            life_texture="有生活感",
            career_intensity="规律稳定",
            exercise_habit="轻运动",
            growth_signal="平台成熟",
            warmth_style="有温度会接话",
            aesthetic_expression="有生活审美",
            conversation_resonance="会接话也会接情绪",
            personal_presence="温和耐看",
            blended_family_readiness="已想过现实安排",
            accept_marital_status="未婚, 离异未育, 离异已育",
            accept_marital_status_strength="明确接受",
            accept_partner_children="接受",
            accept_partner_children_strength="明确接受",
            verified_level="id",
            last_active_at=now - timedelta(minutes=40),
        ),
        base_profile(
            profile_id=30007,
            name="沈越川",
            gender="男",
            age=36,
            city="杭州",
            district="拱墅区",
            height=178,
            education="硕士",
            job="法务经理",
            income_min=32,
            income_max=50,
            relationship_goal="结婚导向",
            personality="情绪稳定, 温和, 有责任感",
            values="重视家庭, 边界清楚, 愿意共同经营生活",
            lifestyle="规律作息, 爱运动, 喜欢做饭",
            hobbies="羽毛球, 阅读, 咖啡",
            notes="更看重现实配合度，愿意一起商量孩子、见面频率和家庭安排",
            preferred_age_min=31,
            preferred_age_max=38,
            preferred_height_min=155,
            preferred_height_max=170,
            preferred_education_min="本科",
            preferred_income_min_wan=18,
            preferred_income_max_wan=80,
            life_routine="生活规律",
            communication_style="主动沟通",
            dating_pace="认真推进",
            expression_style="会表达有生活感",
            relationship_capacity="稳定投入关系",
            interaction_comfort="有边界不拧巴",
            patience_level="耐心稳定",
            life_texture="有见识也有生活感",
            career_intensity="规律稳定",
            exercise_habit="规律运动",
            growth_signal="平台成熟",
            warmth_style="理性但不冷",
            aesthetic_expression="有生活审美",
            conversation_resonance="能聊想法也能聊日常",
            personal_presence="温和耐看",
            blended_family_readiness="已想过现实安排",
            accept_marital_status="未婚, 离异未育, 离异已育",
            accept_marital_status_strength="明确接受",
            accept_partner_children="接受",
            accept_partner_children_strength="明确接受",
            verified_level="offline",
            last_active_at=now - timedelta(hours=6),
        ),
        base_profile(
            profile_id=30008,
            name="林乔安",
            gender="女",
            age=34,
            city="苏州",
            district="工业园区",
            height=166,
            education="硕士",
            job="教师",
            income_min=22,
            income_max=36,
            relationship_goal="结婚导向",
            personality="情绪稳定, 有耐心, 真诚",
            values="重视家庭, 愿意共同经营生活, 稳定踏实",
            lifestyle="生活规律, 喜欢做饭, 周末会出门走走",
            hobbies="电影, 烘焙, 散步",
            notes="能理解再婚和孩子安排，愿意在见面频率、孩子节奏和双方边界上提前商量",
            preferred_age_min=33,
            preferred_age_max=42,
            preferred_height_min=170,
            preferred_height_max=186,
            preferred_education_min="本科",
            preferred_income_min_wan=30,
            preferred_income_max_wan=70,
            life_routine="生活规律",
            communication_style="稳定沟通",
            dating_pace="认真推进",
            expression_style="自然表达",
            relationship_capacity="稳定投入关系",
            interaction_comfort="相处轻松",
            patience_level="高耐心",
            life_texture="有见识也有生活感",
            career_intensity="规律稳定",
            exercise_habit="轻运动",
            growth_signal="平台成熟",
            warmth_style="有温度会接话",
            aesthetic_expression="有生活审美",
            conversation_resonance="会接话也会接情绪",
            personal_presence="温和耐看",
            blended_family_readiness="已想过现实安排",
            accept_marital_status="未婚, 离异未育, 离异已育",
            accept_marital_status_strength="明确接受",
            accept_partner_children="接受",
            accept_partner_children_strength="明确接受",
            verified_level="offline",
            last_active_at=now - timedelta(minutes=20),
        ),
        base_profile(
            profile_id=30009,
            name="方舒宁",
            gender="女",
            age=35,
            city="苏州",
            district="姑苏区",
            height=165,
            education="本科",
            job="会计",
            income_min=18,
            income_max=28,
            relationship_goal="认真恋爱",
            personality="温和, 情绪稳定, 有耐心",
            values="重视家庭, 消费观正常, 愿意共同经营生活",
            lifestyle="规律作息, 偏宅, 喜欢做饭",
            hobbies="桌游, 旅行, 瑜伽",
            notes="可以接受对方有孩子，但更希望把见面节奏和现实安排聊清楚再推进",
            preferred_age_min=33,
            preferred_age_max=42,
            preferred_height_min=170,
            preferred_height_max=186,
            preferred_education_min="本科",
            preferred_income_min_wan=25,
            preferred_income_max_wan=70,
            life_routine="生活规律",
            communication_style="稳定沟通",
            dating_pace="自然推进",
            expression_style="自然表达",
            relationship_capacity="稳定投入关系",
            interaction_comfort="安静低压",
            patience_level="高耐心",
            life_texture="有生活感",
            career_intensity="规律稳定",
            exercise_habit="轻运动",
            growth_signal="平台成熟",
            warmth_style="理性但不冷",
            aesthetic_expression="有生活审美",
            conversation_resonance="偏务实日常",
            personal_presence="温和耐看",
            blended_family_readiness="愿意一起商量",
            accept_marital_status="未婚, 离异未育, 离异已育",
            accept_marital_status_strength="明确接受",
            accept_partner_children="接受",
            accept_partner_children_strength="明确接受",
            verified_level="id",
            last_active_at=now - timedelta(hours=9),
        ),
        base_profile(
            profile_id=30010,
            name="周砚川",
            gender="男",
            age=36,
            city="无锡",
            district="滨湖区",
            height=179,
            education="硕士",
            job="法务",
            income_min=28,
            income_max=46,
            relationship_goal="结婚导向",
            personality="情绪稳定, 理性, 温和",
            values="对感情认真, 稳定踏实, 消费观正常",
            lifestyle="规律作息, 喜欢做饭, 爱运动",
            hobbies="阅读, 徒步, 看展",
            notes="对婚史不设偏见，更看对方现在有没有稳定投入关系的能力",
            preferred_age_min=31,
            preferred_age_max=36,
            preferred_height_min=158,
            preferred_height_max=170,
            preferred_education_min="本科",
            preferred_income_min_wan=18,
            preferred_income_max_wan=70,
            life_routine="生活规律",
            communication_style="稳定沟通",
            dating_pace="认真推进",
            expression_style="会表达有生活感",
            relationship_capacity="稳定投入关系",
            interaction_comfort="有边界不拧巴",
            patience_level="耐心稳定",
            life_texture="有见识也有生活感",
            career_intensity="规律稳定",
            exercise_habit="规律运动",
            growth_signal="平台成熟",
            warmth_style="理性但不冷",
            aesthetic_expression="有生活审美",
            conversation_resonance="能聊想法也能聊日常",
            personal_presence="有记忆点",
            blended_family_readiness="愿意一起商量",
            accept_marital_status="未婚, 离异未育",
            accept_marital_status_strength="明确接受",
            accept_partner_children="可协商",
            accept_partner_children_strength="短期可聊",
            verified_level="id",
            last_active_at=now - timedelta(hours=4),
        ),
        base_profile(
            profile_id=30011,
            name="顾承润",
            gender="男",
            age=30,
            city="嘉兴",
            district="南湖区",
            height=177,
            education="本科",
            job="药师",
            income_min=18,
            income_max=28,
            relationship_goal="认真恋爱",
            personality="情绪稳定, 有耐心, 温和",
            values="简单真诚, 愿意共同经营生活, 稳定踏实",
            lifestyle="生活规律, 养生, 周末会出门走走",
            hobbies="散步, 咖啡, 电影",
            notes="不喜欢高压拉扯，比较看重相处舒服，慢一点也没关系",
            preferred_age_min=27,
            preferred_age_max=31,
            preferred_height_min=155,
            preferred_height_max=168,
            preferred_education_min="本科",
            preferred_income_min_wan=12,
            preferred_income_max_wan=40,
            life_routine="生活规律",
            communication_style="稳定沟通",
            dating_pace="自然推进",
            expression_style="自然表达",
            relationship_capacity="自然稳定投入",
            interaction_comfort="相处轻松",
            patience_level="高耐心",
            life_texture="有生活感",
            career_intensity="常规稳定",
            exercise_habit="轻运动",
            growth_signal="稳步发展",
            warmth_style="有温度会接话",
            aesthetic_expression="有生活审美",
            conversation_resonance="会接话也会接情绪",
            personal_presence="温和耐看",
            blended_family_readiness="愿意一起商量",
            long_distance="不接受",
            accept_long_distance="不接受",
            verified_level="id",
            last_active_at=now - timedelta(minutes=55),
        ),
        base_profile(
            profile_id=30012,
            name="陆知远",
            gender="男",
            age=31,
            city="嘉兴",
            district="秀洲区",
            height=179,
            education="硕士",
            job="教师",
            income_min=20,
            income_max=34,
            relationship_goal="认真恋爱",
            personality="真诚, 有耐心, 安静",
            values="简单真诚, 稳定踏实, 能沟通",
            lifestyle="规律作息, 喜欢做饭, 偏宅",
            hobbies="阅读, 桌游, 徒步",
            notes="慢热但会接住话，不会逼着推进，更希望先把相处感建立起来",
            preferred_age_min=27,
            preferred_age_max=31,
            preferred_height_min=155,
            preferred_height_max=168,
            preferred_education_min="本科",
            preferred_income_min_wan=12,
            preferred_income_max_wan=45,
            life_routine="生活规律",
            communication_style="稳定沟通",
            dating_pace="慢热推进",
            expression_style="自然表达",
            relationship_capacity="先熟悉再投入",
            interaction_comfort="安静低压",
            patience_level="高耐心",
            life_texture="有生活感",
            career_intensity="规律稳定",
            exercise_habit="轻运动",
            growth_signal="平台成熟",
            warmth_style="理性但不冷",
            aesthetic_expression="有生活审美",
            conversation_resonance="会接话也会接情绪",
            personal_presence="温和耐看",
            blended_family_readiness="愿意一起商量",
            long_distance="不接受",
            accept_long_distance="不接受",
            verified_level="offline",
            last_active_at=now - timedelta(hours=8),
        ),
        base_profile(
            profile_id=30013,
            name="江芷岚",
            gender="女",
            age=30,
            city="苏州",
            district="吴中区",
            height=168,
            education="硕士",
            job="法务",
            income_min=24,
            income_max=38,
            relationship_goal="结婚导向",
            personality="情绪稳定, 理性, 有耐心",
            values="消费观正常, 边界清楚, 尊重彼此空间",
            lifestyle="规律作息, 喜欢做饭, 爱运动",
            hobbies="阅读, 羽毛球, 看展",
            notes="不喜欢拧巴关系，比较看重边界感、长期省心和稳定推进",
            preferred_age_min=30,
            preferred_age_max=36,
            preferred_height_min=176,
            preferred_height_max=188,
            preferred_education_min="本科",
            preferred_income_min_wan=30,
            preferred_income_max_wan=80,
            life_routine="生活规律",
            communication_style="理性直接",
            dating_pace="认真推进",
            expression_style="会表达有生活感",
            relationship_capacity="稳定投入关系",
            interaction_comfort="有边界不拧巴",
            patience_level="耐心稳定",
            life_texture="有见识也有生活感",
            career_intensity="规律稳定",
            exercise_habit="规律运动",
            growth_signal="平台成熟",
            warmth_style="理性但不冷",
            aesthetic_expression="有生活审美",
            conversation_resonance="偏务实日常",
            personal_presence="温和耐看",
            blended_family_readiness="愿意一起商量",
            verified_level="id",
            last_active_at=now - timedelta(minutes=35),
        ),
        base_profile(
            profile_id=30014,
            name="韩叙川",
            gender="男",
            age=33,
            city="宁波",
            district="鄞州区",
            height=181,
            education="硕士",
            job="商业分析经理",
            income_min=38,
            income_max=62,
            relationship_goal="结婚导向",
            personality="情绪稳定, 有责任感, 真诚",
            values="不拜金, 对感情认真, 愿意共同经营生活",
            lifestyle="规律作息, 爱运动, 偶尔短途旅行",
            hobbies="徒步, 阅读, 游泳",
            notes="不排斥另一半事业心强，既能聊工作判断，也能把生活过得不紧绷",
            preferred_age_min=28,
            preferred_age_max=34,
            preferred_height_min=160,
            preferred_height_max=172,
            preferred_education_min="本科",
            preferred_income_min_wan=25,
            preferred_income_max_wan=100,
            life_routine="生活规律",
            communication_style="主动沟通",
            dating_pace="认真推进",
            expression_style="会表达有生活感",
            relationship_capacity="稳定投入关系",
            interaction_comfort="有边界不拧巴",
            patience_level="耐心稳定",
            life_texture="有见识也有生活感",
            career_intensity="脑力投入型",
            exercise_habit="规律运动",
            growth_signal="上升明确",
            warmth_style="理性但不冷",
            aesthetic_expression="有生活审美",
            conversation_resonance="能聊想法也能聊日常",
            personal_presence="有记忆点",
            blended_family_readiness="愿意一起商量",
            verified_level="offline",
            last_active_at=now - timedelta(hours=3, minutes=20),
        ),
        base_profile(
            profile_id=30015,
            name="罗佳宜",
            gender="女",
            age=29,
            city="苏州",
            district="工业园区",
            height=165,
            education="硕士",
            job="用户研究",
            income_min=20,
            income_max=32,
            relationship_goal="认真恋爱",
            personality="情绪稳定, 温和, 细腻",
            values="消费观正常, 边界清楚, 愿意共同经营生活",
            lifestyle="规律作息, 喜欢咖啡馆, 周末会出门走走",
            hobbies="看展, 阅读, 咖啡",
            notes="不喜欢情绪拉扯，比较看重边界清楚、聊天顺和相处省心",
            preferred_age_min=29,
            preferred_age_max=35,
            preferred_height_min=176,
            preferred_height_max=188,
            preferred_education_min="本科",
            preferred_income_min_wan=28,
            preferred_income_max_wan=70,
            life_routine="生活规律",
            communication_style="稳定沟通",
            dating_pace="自然推进",
            expression_style="会表达有生活感",
            relationship_capacity="稳定投入关系",
            interaction_comfort="相处轻松",
            patience_level="高耐心",
            life_texture="有见识也有生活感",
            career_intensity="脑力投入型",
            exercise_habit="轻运动",
            growth_signal="平台成熟",
            warmth_style="有温度会接话",
            aesthetic_expression="有审美输出",
            conversation_resonance="能聊想法也能聊日常",
            personal_presence="有记忆点",
            blended_family_readiness="愿意一起商量",
            verified_level="id",
            last_active_at=now - timedelta(hours=1, minutes=30),
        ),
        base_profile(
            profile_id=30016,
            name="季沉川",
            gender="男",
            age=34,
            city="上海",
            district="黄浦区",
            height=182,
            education="硕士",
            job="战略咨询经理",
            income_min=52,
            income_max=78,
            relationship_goal="结婚导向",
            personality="情绪稳定, 真诚, 有耐心",
            values="消费观正常, 对感情认真, 愿意共同经营生活",
            lifestyle="规律作息, 喜欢做饭, 周末会出门走走",
            hobbies="阅读, 播客, 看展",
            notes="说话不端着，既能聊工作判断，也会分享日常小事和好玩的展，希望两个人越聊越有感觉",
            preferred_age_min=28,
            preferred_age_max=34,
            preferred_height_min=160,
            preferred_height_max=174,
            preferred_education_min="本科",
            preferred_income_min_wan=22,
            preferred_income_max_wan=130,
            life_routine="生活规律",
            communication_style="主动沟通",
            dating_pace="认真推进",
            expression_style="会表达有生活感",
            relationship_capacity="稳定投入关系",
            interaction_comfort="相处轻松",
            patience_level="高耐心",
            life_texture="有见识也有生活感",
            career_intensity="脑力投入型",
            exercise_habit="规律运动",
            growth_signal="上升明确",
            warmth_style="有温度会接话",
            aesthetic_expression="有审美输出",
            conversation_resonance="能聊想法也能聊日常",
            personal_presence="有记忆点",
            blended_family_readiness="愿意一起商量",
            accept_marital_status="未婚, 离异未育",
            verified_level="offline",
            last_active_at=now - timedelta(minutes=15),
        ),
        base_profile(
            profile_id=30017,
            name="闻时越",
            gender="男",
            age=29,
            city="上海",
            district="静安区",
            height=179,
            education="硕士",
            job="内容策略经理",
            income_min=30,
            income_max=48,
            relationship_goal="认真恋爱",
            personality="情绪稳定, 善沟通, 细腻",
            values="消费观正常, 能沟通, 尊重彼此空间",
            lifestyle="规律作息, 喜欢咖啡馆, 周末会出门走走",
            hobbies="看展, 摄影, 电影",
            notes="会把展览、播客和餐馆聊得有趣，也愿意认真回应对方情绪，不喜欢端着相处",
            preferred_age_min=25,
            preferred_age_max=31,
            preferred_height_min=158,
            preferred_height_max=173,
            preferred_education_min="本科",
            preferred_income_min_wan=18,
            preferred_income_max_wan=90,
            life_routine="生活规律",
            communication_style="主动沟通",
            dating_pace="自然推进",
            expression_style="会表达有生活感",
            relationship_capacity="自然稳定投入",
            interaction_comfort="相处轻松",
            patience_level="耐心稳定",
            life_texture="有见识也有生活感",
            career_intensity="脑力投入型",
            exercise_habit="轻运动",
            growth_signal="稳步发展",
            warmth_style="有温度会接话",
            aesthetic_expression="有审美输出",
            conversation_resonance="能聊想法也能聊日常",
            personal_presence="有记忆点",
            blended_family_readiness="愿意一起商量",
            verified_level="offline",
            last_active_at=now - timedelta(minutes=25),
        ),
        base_profile(
            profile_id=30018,
            name="梁怀瑾",
            gender="男",
            age=34,
            city="宁波",
            district="鄞州区",
            height=183,
            education="硕士",
            job="业务发展负责人",
            income_min=46,
            income_max=72,
            relationship_goal="结婚导向",
            personality="情绪稳定, 有责任感, 真诚",
            values="不拜金, 对感情认真, 愿意共同经营生活",
            lifestyle="规律作息, 爱运动, 喜欢做饭",
            hobbies="游泳, 阅读, 咖啡",
            notes="不介意另一半事业心强，能聊判断也能聊日常，不会把关系做成高压 KPI",
            preferred_age_min=29,
            preferred_age_max=35,
            preferred_height_min=160,
            preferred_height_max=173,
            preferred_education_min="本科",
            preferred_income_min_wan=24,
            preferred_income_max_wan=120,
            life_routine="生活规律",
            communication_style="主动沟通",
            dating_pace="认真推进",
            expression_style="会表达有生活感",
            relationship_capacity="稳定投入关系",
            interaction_comfort="有边界不拧巴",
            patience_level="耐心稳定",
            life_texture="有见识也有生活感",
            career_intensity="脑力投入型",
            exercise_habit="规律运动",
            growth_signal="上升明确",
            warmth_style="理性但不冷",
            aesthetic_expression="有生活审美",
            conversation_resonance="能聊想法也能聊日常",
            personal_presence="有记忆点",
            blended_family_readiness="愿意一起商量",
            verified_level="id",
            last_active_at=now - timedelta(minutes=10),
        ),
        base_profile(
            profile_id=30019,
            name="陈柏舟",
            gender="男",
            age=35,
            city="无锡",
            district="梁溪区",
            height=178,
            education="硕士",
            job="高校教师",
            income_min=24,
            income_max=38,
            relationship_goal="结婚导向",
            personality="情绪稳定, 温和, 真诚",
            values="重视家庭, 稳定踏实, 对感情认真",
            lifestyle="规律作息, 喜欢做饭, 偏宅",
            hobbies="阅读, 散步, 电影",
            notes="对婚史不敏感，更看重对方现在是不是稳定、坦诚、愿意认真经营关系",
            preferred_age_min=31,
            preferred_age_max=36,
            preferred_height_min=158,
            preferred_height_max=170,
            preferred_education_min="本科",
            preferred_income_min_wan=15,
            preferred_income_max_wan=70,
            life_routine="生活规律",
            communication_style="稳定沟通",
            dating_pace="认真推进",
            expression_style="自然表达",
            relationship_capacity="稳定投入关系",
            interaction_comfort="安静低压",
            patience_level="耐心稳定",
            life_texture="有生活感",
            career_intensity="规律稳定",
            exercise_habit="轻运动",
            growth_signal="平台成熟",
            warmth_style="有温度会接话",
            aesthetic_expression="有生活审美",
            conversation_resonance="偏务实日常",
            personal_presence="温和耐看",
            blended_family_readiness="愿意一起商量",
            accept_marital_status="未婚, 离异未育",
            accept_marital_status_strength="明确接受",
            verified_level="id",
            last_active_at=now - timedelta(minutes=50),
        ),
        base_profile(
            profile_id=30020,
            name="许清和",
            gender="女",
            age=32,
            city="南通",
            district="崇川区",
            height=164,
            education="本科",
            job="教师",
            income_min=16,
            income_max=24,
            relationship_goal="结婚导向",
            personality="情绪稳定, 真诚, 好相处",
            values="消费观正常, 稳定踏实, 重视家庭",
            lifestyle="生活规律, 喜欢做饭, 周末会出门走走",
            hobbies="电影, 散步, 烘焙",
            notes="更喜欢直给和省心的相处，不爱拧巴，也不想反复试探彼此心意",
            preferred_age_min=32,
            preferred_age_max=38,
            preferred_height_min=170,
            preferred_height_max=186,
            preferred_education_min="本科",
            preferred_income_min_wan=18,
            preferred_income_max_wan=55,
            life_routine="生活规律",
            communication_style="稳定沟通",
            dating_pace="认真推进",
            expression_style="自然表达",
            relationship_capacity="稳定投入关系",
            interaction_comfort="相处轻松",
            patience_level="耐心稳定",
            life_texture="有生活感",
            career_intensity="规律稳定",
            exercise_habit="轻运动",
            growth_signal="平台成熟",
            warmth_style="有温度会接话",
            aesthetic_expression="有生活审美",
            conversation_resonance="会接话也会接情绪",
            personal_presence="温和耐看",
            blended_family_readiness="愿意一起商量",
            verified_level="id",
            last_active_at=now - timedelta(minutes=30),
        ),
        base_profile(
            profile_id=30021,
            name="周既白",
            gender="女",
            age=30,
            city="苏州",
            district="工业园区",
            height=167,
            education="硕士",
            job="财务BP",
            income_min=26,
            income_max=40,
            relationship_goal="结婚导向",
            personality="情绪稳定, 理性, 温和",
            values="消费观正常, 边界清楚, 尊重彼此空间",
            lifestyle="规律作息, 爱运动, 喜欢做饭",
            hobbies="阅读, 咖啡, 羽毛球",
            notes="边界清楚但不冷，有事会直说，也能把生活过得轻松一点，不喜欢情绪拉扯",
            preferred_age_min=30,
            preferred_age_max=36,
            preferred_height_min=176,
            preferred_height_max=188,
            preferred_education_min="本科",
            preferred_income_min_wan=30,
            preferred_income_max_wan=85,
            life_routine="生活规律",
            communication_style="理性直接",
            dating_pace="认真推进",
            expression_style="会表达有生活感",
            relationship_capacity="稳定投入关系",
            interaction_comfort="有边界不拧巴",
            patience_level="耐心稳定",
            life_texture="有见识也有生活感",
            career_intensity="脑力投入型",
            exercise_habit="规律运动",
            growth_signal="平台成熟",
            warmth_style="理性但不冷",
            aesthetic_expression="有生活审美",
            conversation_resonance="能聊想法也能聊日常",
            personal_presence="温和耐看",
            blended_family_readiness="愿意一起商量",
            verified_level="offline",
            last_active_at=now - timedelta(minutes=18),
        ),
        base_profile(
            profile_id=30022,
            name="梁砚知",
            gender="男",
            age=32,
            city="南京",
            district="建邺区",
            height=181,
            education="博士",
            job="政策研究员",
            income_min=55,
            income_max=82,
            relationship_goal="结婚导向",
            personality="情绪稳定, 理性, 有主见",
            values="消费观正常, 对感情认真, 愿意共同经营生活",
            lifestyle="规律作息, 喜欢做饭, 周末会出门走走",
            hobbies="阅读, 看展, 咖啡",
            notes="能把现实计划说清，也能聊书、城市和想法，不会只剩条件匹配，聊天里有分寸也有内容",
            preferred_age_min=27,
            preferred_age_max=34,
            preferred_height_min=160,
            preferred_height_max=173,
            preferred_education_min="硕士",
            preferred_income_min_wan=35,
            preferred_income_max_wan=130,
            life_routine="生活规律",
            communication_style="主动沟通",
            dating_pace="认真推进",
            expression_style="会表达有生活感",
            relationship_capacity="稳定投入关系",
            interaction_comfort="有边界不拧巴",
            patience_level="耐心稳定",
            life_texture="有见识也有生活感",
            career_intensity="脑力投入型",
            exercise_habit="规律运动",
            growth_signal="上升明确",
            warmth_style="理性但不冷",
            aesthetic_expression="有审美输出",
            conversation_resonance="能聊想法也能聊日常",
            personal_presence="有记忆点",
            blended_family_readiness="愿意一起商量",
            verified_level="id",
            last_active_at=now - timedelta(minutes=8),
        ),
        base_profile(
            profile_id=30023,
            name="沈知行",
            gender="女",
            age=31,
            city="常州",
            district="天宁区",
            height=165,
            education="本科",
            job="教师",
            income_min=16,
            income_max=25,
            relationship_goal="结婚导向",
            personality="情绪稳定, 顾家, 真诚",
            values="重视家庭, 稳定踏实, 愿意共同经营生活",
            lifestyle="生活规律, 喜欢做饭, 偏宅",
            hobbies="散步, 电影, 烘焙",
            notes="更相信两个人把日子过稳，不喜欢情绪拉扯，愿意认真经营家庭和日常",
            preferred_age_min=30,
            preferred_age_max=36,
            preferred_height_min=170,
            preferred_height_max=186,
            preferred_education_min="本科",
            preferred_income_min_wan=18,
            preferred_income_max_wan=60,
            life_routine="生活规律",
            communication_style="稳定沟通",
            dating_pace="认真推进",
            expression_style="自然表达",
            relationship_capacity="稳定投入关系",
            interaction_comfort="相处轻松",
            patience_level="耐心稳定",
            life_texture="有生活感",
            career_intensity="规律稳定",
            exercise_habit="轻运动",
            growth_signal="平台成熟",
            warmth_style="有温度会接话",
            aesthetic_expression="有生活审美",
            conversation_resonance="偏务实日常",
            personal_presence="温和耐看",
            blended_family_readiness="愿意一起商量",
            verified_level="offline",
            last_active_at=now - timedelta(minutes=45),
        ),
        base_profile(
            profile_id=30024,
            name="苏念远",
            gender="女",
            age=35,
            city="苏州",
            district="高新区",
            height=166,
            education="硕士",
            job="心理咨询师",
            income_min=22,
            income_max=34,
            relationship_goal="结婚导向",
            personality="情绪稳定, 真诚, 有耐心",
            values="重视家庭, 愿意共同经营生活, 边界清楚",
            lifestyle="生活规律, 喜欢做饭, 周末会出门走走",
            hobbies="阅读, 散步, 瑜伽",
            notes="知道再婚不是一句接受就够，会先把孩子、老人、时间安排和彼此边界聊明白再推进",
            preferred_age_min=34,
            preferred_age_max=42,
            preferred_height_min=170,
            preferred_height_max=186,
            preferred_education_min="本科",
            preferred_income_min_wan=28,
            preferred_income_max_wan=75,
            life_routine="生活规律",
            communication_style="稳定沟通",
            dating_pace="认真推进",
            expression_style="自然表达",
            relationship_capacity="稳定投入关系",
            interaction_comfort="相处轻松",
            patience_level="高耐心",
            life_texture="有见识也有生活感",
            career_intensity="规律稳定",
            exercise_habit="轻运动",
            growth_signal="平台成熟",
            warmth_style="有温度会接话",
            aesthetic_expression="有生活审美",
            conversation_resonance="会接话也会接情绪",
            personal_presence="温和耐看",
            blended_family_readiness="已想过现实安排",
            accept_marital_status="未婚, 离异未育, 离异已育",
            accept_marital_status_strength="明确接受",
            accept_partner_children="接受",
            accept_partner_children_strength="明确接受",
            verified_level="offline",
            last_active_at=now - timedelta(minutes=12),
        ),
        base_profile(
            profile_id=30025,
            name="蒋知白",
            gender="男",
            age=31,
            city="无锡",
            district="滨湖区",
            height=176,
            education="本科",
            job="公务员",
            income_min=18,
            income_max=28,
            relationship_goal="结婚导向",
            personality="情绪稳定, 有耐心, 温和",
            values="简单真诚, 稳定踏实, 重视家庭",
            lifestyle="生活规律, 养生, 偏宅",
            hobbies="散步, 阅读, 羽毛球",
            notes="慢热但会接住话，不爱花哨表达，比较擅长把相处做得舒服、稳定、不累",
            preferred_age_min=27,
            preferred_age_max=31,
            preferred_height_min=158,
            preferred_height_max=170,
            preferred_education_min="本科",
            preferred_income_min_wan=12,
            preferred_income_max_wan=45,
            life_routine="生活规律",
            communication_style="稳定沟通",
            dating_pace="慢热推进",
            expression_style="自然表达",
            relationship_capacity="稳定投入关系",
            interaction_comfort="安静低压",
            patience_level="高耐心",
            life_texture="有生活感",
            career_intensity="规律稳定",
            exercise_habit="轻运动",
            growth_signal="平台成熟",
            warmth_style="有温度会接话",
            aesthetic_expression="有生活审美",
            conversation_resonance="会接话也会接情绪",
            personal_presence="温和耐看",
            blended_family_readiness="愿意一起商量",
            verified_level="id",
            last_active_at=now - timedelta(minutes=28),
        ),
    ]


def ensure_columns(conn, table_name):
    with conn.cursor() as cursor:
        cursor.execute(f"SHOW COLUMNS FROM `{table_name}`")
        existing = {row[0] for row in cursor.fetchall()}
        for column, column_type in {**ALL_NEW_COLUMNS, **STRUCTURED_COLUMN_TYPES}.items():
            if column not in existing:
                cursor.execute(f"ALTER TABLE `{table_name}` ADD COLUMN `{column}` {column_type} NULL")


def upsert_profiles(conn, table_name, profiles):
    placeholders = ", ".join(["%s"] * len(PROFILE_COLUMNS))
    column_sql = ", ".join(f"`{column}`" for column in PROFILE_COLUMNS)
    update_sql = ", ".join(
        f"`{column}`=VALUES(`{column}`)" for column in PROFILE_COLUMNS if column != "id"
    )
    sql = (
        f"INSERT INTO `{table_name}` ({column_sql}) VALUES ({placeholders}) "
        f"ON DUPLICATE KEY UPDATE {update_sql}"
    )
    rows = [tuple(profile[column] for column in PROFILE_COLUMNS) for profile in profiles]
    with conn.cursor() as cursor:
        cursor.executemany(sql, rows)


def replace_photos(conn, table_name, profiles):
    profile_ids = [profile["id"] for profile in profiles]
    delete_placeholders = ", ".join(["%s"] * len(profile_ids))
    photo_rows = []
    for profile in profiles:
        photo_rows.extend(make_photo_rows(profile))
    insert_columns = [
        "profile_id",
        "photo_url",
        "photo_type",
        "sort_order",
        "is_primary",
        "created_at",
        "updated_at",
    ]
    insert_sql = (
        f"INSERT INTO `{table_name}` ({', '.join(f'`{column}`' for column in insert_columns)}) "
        f"VALUES ({', '.join(['%s'] * len(insert_columns))})"
    )
    with conn.cursor() as cursor:
        cursor.execute(
            f"DELETE FROM `{table_name}` WHERE `profile_id` IN ({delete_placeholders})",
            profile_ids,
        )
        cursor.executemany(
            insert_sql,
            [tuple(row[column] for column in insert_columns) for row in photo_rows],
        )


def main():
    args = parse_args()
    try:
        import pymysql
    except ImportError as exc:  # pragma: no cover
        raise SystemExit("PyMySQL is required to seed gap profiles.") from exc

    profiles = build_profiles()
    conn = pymysql.connect(
        host=args.host,
        port=args.port,
        user=args.user,
        password=args.password,
        database=args.database,
        charset=args.charset,
        autocommit=False,
    )
    try:
        ensure_columns(conn, args.table)
        upsert_profiles(conn, args.table, profiles)
        replace_photos(conn, args.photos_table, profiles)
        conn.commit()
        print(f"Seeded {len(profiles)} curated profiles into {args.database}.{args.table}")
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


if __name__ == "__main__":
    main()
