"""External Phase 3/4 recommendation system built on top of partner-search."""

from .direct_greet_gate import (
    DEFAULT_MAX_REVIEW_CANDIDATES_PER_REFRESH,
    DEFAULT_MIN_DIRECT_GREET_SCORE,
    DEFAULT_RECOMMENDATION_MODE,
)
from .no_match_opt_in import (
    DEFAULT_NO_MATCH_OPT_IN_PROMPT,
    handle_opt_in_decision,
    run_search_session,
    subscribe_after_opt_in,
)
from .proxy_intro import (
    DEFAULT_DECLINE_COOLDOWN_DAYS,
    DEFAULT_OUTREACH_CHANNEL,
    DEFAULT_REPLY_WINDOW_HOURS,
    DEFAULT_TIMEOUT_COOLDOWN_DAYS,
    build_safe_summary,
    close_match_case,
    close_timed_out_match_cases,
    create_match_case,
    dispatch_match_case_outreach,
    dispatch_pending_match_cases,
    get_active_match_case_for_recommendation,
    get_latest_match_case_for_recommendation,
    get_match_case,
    list_match_case_events,
    list_match_case_outreach_attempts,
    list_match_cases_for_recommendation,
    list_match_cases_for_subscription,
    record_match_case_reply,
)
from .service import (
    build_in_app_card,
    create_subscription,
    deliver_in_app_recommendations,
    get_subscription,
    list_in_app_cards,
    list_search_runs_for_subscription,
    list_recommendations_for_subscription,
    record_recommendation_action,
    record_user_review,
    refresh_due_subscriptions,
    refresh_subscription,
    update_subscription_overrides,
)
from .storage import connect_db, initialize_database

__all__ = [
    "DEFAULT_MAX_REVIEW_CANDIDATES_PER_REFRESH",
    "DEFAULT_DECLINE_COOLDOWN_DAYS",
    "DEFAULT_MIN_DIRECT_GREET_SCORE",
    "DEFAULT_OUTREACH_CHANNEL",
    "DEFAULT_RECOMMENDATION_MODE",
    "DEFAULT_NO_MATCH_OPT_IN_PROMPT",
    "DEFAULT_REPLY_WINDOW_HOURS",
    "DEFAULT_TIMEOUT_COOLDOWN_DAYS",
    "build_in_app_card",
    "build_safe_summary",
    "connect_db",
    "close_match_case",
    "close_timed_out_match_cases",
    "create_match_case",
    "create_subscription",
    "dispatch_match_case_outreach",
    "dispatch_pending_match_cases",
    "deliver_in_app_recommendations",
    "get_active_match_case_for_recommendation",
    "get_latest_match_case_for_recommendation",
    "get_match_case",
    "get_subscription",
    "handle_opt_in_decision",
    "initialize_database",
    "list_in_app_cards",
    "list_match_case_events",
    "list_match_case_outreach_attempts",
    "list_match_cases_for_recommendation",
    "list_match_cases_for_subscription",
    "list_recommendations_for_subscription",
    "list_search_runs_for_subscription",
    "record_match_case_reply",
    "record_recommendation_action",
    "record_user_review",
    "refresh_due_subscriptions",
    "refresh_subscription",
    "run_search_session",
    "subscribe_after_opt_in",
    "update_subscription_overrides",
]
