"""Shared role groups for gateway authorization checks."""

from __future__ import annotations

from .identity import (
    ROLE_CUSTOMER_SUPPORT,
    ROLE_OPS_OPERATOR,
    ROLE_PLATFORM_ADMIN,
    ROLE_PROFILE_REVIEWER,
    ROLE_RISK_REVIEWER,
    ROLE_SERVICE_WORKER,
)

STAFF_OVERRIDE_ROLES = frozenset(
    {
        ROLE_OPS_OPERATOR,
        ROLE_RISK_REVIEWER,
        ROLE_PROFILE_REVIEWER,
        ROLE_CUSTOMER_SUPPORT,
        ROLE_PLATFORM_ADMIN,
        ROLE_SERVICE_WORKER,
    }
)
INTERNAL_WRITE_ROLES = frozenset({ROLE_OPS_OPERATOR, ROLE_PLATFORM_ADMIN, ROLE_SERVICE_WORKER})
VERIFICATION_REVIEW_ROLES = frozenset(
    {
        ROLE_RISK_REVIEWER,
        ROLE_PROFILE_REVIEWER,
        ROLE_PLATFORM_ADMIN,
        ROLE_SERVICE_WORKER,
    }
)
PROFILE_REVIEW_ROLES = frozenset({ROLE_PROFILE_REVIEWER, ROLE_PLATFORM_ADMIN, ROLE_SERVICE_WORKER})
CHAT_RISK_REVIEW_ROLES = frozenset(
    {
        ROLE_RISK_REVIEWER,
        ROLE_CUSTOMER_SUPPORT,
        ROLE_PLATFORM_ADMIN,
        ROLE_SERVICE_WORKER,
    }
)
